name: CI Simple - Docker Build Only

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build frontend Docker image
      run: |
        cd client
        docker build -t scorm-merge-frontend .

    - name: Build backend Docker image
      run: docker build -f Dockerfile.backend -t scorm-merge-backend .

    - name: Build main Docker image
      run: docker build -f Dockerfile -t scorm-merge .

    - name: Verify images were created
      run: |
        docker images | grep scorm-merge
        echo "All Docker images built successfully!"